using System;

namespace Spines.Mahjong.Analysis.Score
{
  [Flags]
  public enum Yaku : long
  {
    None = 0,
    MenzenTsumo = 1L << 0,
    Riichi = 1L << 1,
    Ippatsu = 1L << 2,
    Chankan = 1L << 3,
    RinshanKaihou = 1L << 4,
    HaiteiRaoyue = 1L << 5,
    HouteiRaoyui = 1L << 6,
    Pinfu = 1L << 7,
    OpenTanyao = 1L << 8,
    ClosedTanyao = 1L << 9,
    Iipeikou = 1L << 10,
    JikazeTon = 1L << 11,
    JikazeShaa = 1L << 12,
    JikazeNan = 1L << 13,
    JikazePei = 1L << 14,
    BakazeTon = 1L << 15,
    BakazeShaa = 1L << 16,
    BakazeNan = 1L << 17,
    BakazePei = 1L << 18,
    Haku = 1L << 19,
    Hatsu = 1L << 20,
    Chun = 1L << 21,
    DoubleRiichi = 1L << 22,
    Chiitoitsu = 1L << 23,
    OpenChanta = 1L << 24,
    ClosedChanta = 1L << 25,
    OpenIttsuu = 1L << 26,
    ClosedIttsuu = 1L << 27,
    OpenSanshokuDoujun = 1L << 28,
    ClosedSanshokuDoujun = 1L << 29,
    SanshokuDoukou = 1L << 30,
    Sankantsu = 1L << 31,
    Toitoihou = 1L << 32,
    Sanankou = 1L << 33,
    Shousangen = 1L << 34,
    Honroutou = 1L << 35,
    Ryanpeikou = 1L << 36,
    OpenJunchan = 1L << 37,
    ClosedJunchan = 1L << 38,
    OpenHonitsu = 1L << 39,
    ClosedHonitsu = 1L << 40,
    OpenChinitsu = 1L << 41,
    ClosedChinitsu = 1L << 42,

    Renhou = 1L << 43,
    Tenhou = 1L << 44,
    Chiihou = 1L << 45,
    Daisangen = 1L << 46,
    Suuankou = 1L << 47,
    SuuankouTanki = 1L << 48,
    Tsuuiisou = 1L << 49,
    Ryuuiisou = 1L << 50,
    Chinroutou = 1L << 51,
    ChuurenPoutou = 1L << 52,
    JunseiChuurenPoutou = 1L << 53,
    KokushiMusou = 1L << 54,
    KokushiMusouJuusanMen = 1L << 55,
    Daisuushii = 1L << 56,
    Shousuushii = 1L << 57,
    Suukantsu = 1L << 58,

    Dora = 1L << 59,
    UraDora = 1L << 60,
    AkaDora = 1L << 61
  }
}